### ISSUE TITLE
Show comments doesn't work

### ISSUE THREAD

**Issue by s1037989** [KeystoneIT/Ama#1]
Make it an Ajax thingy that calls $.get('/comments/:question_id/:id') and uses the json response to show and populate a div.

**Comment by JDorpinghaus** [comment]
Added click handler to showcomments div

**Comment by JDorpinghaus** [comment]
Show comments is fully functional

**Comment by JDorpinghaus** [comment]
Comments are only loaded once when needed to eliminate unecessary database queries

**Comment by s1037989** [comment]
Nice work, Jacob!  I look forward to reviewing your code with you next week!
