### ISSUE TITLE
When deleting a question with comments, does that cascade to deleting the comments too?

### ISSUE THREAD

**Issue by s1037989** [KeystoneIT/Ama#129]
The answer to this question is defined by the database, so check migrations/ama.sql.  Look for the cascading options on the create table definition.  Is it set up properly?  May need to cross reference with the Postgresql online documentation.  You may want to also do a test.  Create a question with multiple comments and then delete the question.  Check the database, are the comments gone, as well as the question?

Also check cascading for the other tables: votes, answers, anything else?

**Comment by andygoodday** [comment]
The cascading portion in migrations/ama.sql file of current Dev branch looks good to me. I have created a question with multiple comments. After deleting the question, all comments are gone as well in database. The vote cascading is working as well. It seems like I have to be an admin to delete answered question. On current Dev branch I still get error code 400 when logging in google account, and error 191 when logging in facebook account. Therefore, I didn't test answers cascading. 

I can try to create a foreign key to deal with all the cascading if that is necessary. In my opinion it looks like more precise and neat.

**Comment by s1037989** [comment]
> I have created a question with multiple comments. After deleting the question, all comments are gone as well in database. The vote cascading is working as well. It seems like I have to be an admin to delete answered question.

How did you verify that the comments are gone as well in the database?  The last sentence of the above quote has me skeptical that you queried the database directly.  If you did, that's great!  But the last sentence, as a continuation of the former sentences, leaves me to believe that you verified that the comments are gone by refreshing the Ama webpage.  This is _not_ an acceptable verification.  If the question doesn't exist, the comments will not be retrieved to show in the Ama webpage, but that isn't proof that the comments don't still exist in the database.  This would be referred to as "orphaned" records.

Please verify how you tested and let me know the results after you have queried the database.

Let me know if you have any questions about querying the database, or any of the above lecture in which I comment on orphaned records and why something isn't acceptable.

**Comment by s1037989** [comment]
> I can try to create a foreign key to deal with all the cascading if that is necessary. In my opinion it looks like more precise and neat.

Please tell me more about this!!
