### ISSUE TITLE
Access PUT parameters

### ISSUE THREAD

**Issue by s1037989** [KeystoneIT/Ama#13]
http://mojolicio.us/perldoc/Mojolicious/Guides/Tutorial#GET-POST-parameters

It explicitly states "All GET and POST parameters sent with the request are accessible via "param" in Mojolicious::Controller."

But why not PUT parameters?  Should a PUT request not have parameters at all?

**Comment by JDorpinghaus** [comment]
Setting contentType to "application/x-www-form-urlencoded" allows for parameters to be accessed in a put request.
