### ISSUE TITLE
Account Tune up

### ISSUE THREAD

**Issue by meyerben** [KeystoneIT/Ama#133]
1. show users they are logged in
2. add gravatar feature
3. show users that they're an admin
4. remove account page
5. make admin page
6. move admin tools to admin page
7. popup for logging in to providers on questions page.

**Comment by s1037989** [comment]
Is there anything in this list that isn't done?  Can this issue be closed?

**Comment by meyerben** [comment]
All features are complete assuming oauth2 providers exist in the config
