### ISSUE TITLE
ACLs

### ISSUE THREAD

**Issue by s1037989** [KeystoneIT/Ama#14]
Edit and Delete functions should only be able to be done by the user that originally created the question or comment.  Or users with the admin setting enabled.

Votes can only be given once per entry (question / comment).  This is already done.

Flags can be added by anyone but removed by admins only.

**Comment by jsiems** [comment]
Sort of fixed #61 
RIght now- 
  questions/comments can not be edited
  questions/comments can only be deleted by the one who made it
  no admins exist
  you can only vote once
  flags can be added by anyone and only removed by the one who added them

in the future-
  admins will exist and have full rights to delete, unflag, flag, mark/unmark answers
  maybe a negative vote of -2 will cause a question to disappear, and the flag will be removed  
    completely
