### ISSUE TITLE
Mark a comment as an answer

### ISSUE THREAD

**Issue by s1037989** [KeystoneIT/Ama#2]
From the Show Comments display, each comment should show an Ajax option ($.post('/comments/:question_id/:id/answer')) to mark the comment as the answer.

There's currently no API to unmark a comment as an answer or change the answer mark from one comment to another.  Will create an issue for this.

**Comment by JDorpinghaus** [comment]
Click handler is implemented and routed properly

**Comment by JDorpinghaus** [comment]
Clicking the mark answer button will store the current timestamp in the "answered" section of the comment row in the comment table
