### ISSUE TITLE
Date width should be uniform for questions / comments

### ISSUE THREAD

**Issue by s1037989** [KeystoneIT/Ama#21]
![selection_154](https://cloud.githubusercontent.com/assets/517498/8172321/29a4b61a-1385-11e5-843c-2d5352522b5f.png)

**Comment by JDorpinghaus** [comment]
Date, comment voting buttons, vote count, mark answer, and delete buttons are all centered and of uniform width regardless of comment length (Delete button is only visible if the user created the comment).
![snip](https://cloud.githubusercontent.com/assets/9485088/8187901/2db2c65a-1418-11e5-848d-c63f90de1da1.PNG)
