### ISSUE TITLE
Internet Explorer compatibility

### ISSUE THREAD

**Issue by JDorpinghaus** [KeystoneIT/Ama#35]
The main problem is the use of HTML flexboxes. Update the CSS declarations and replace unsupported elements.

**Comment by JDorpinghaus** [comment]
Added deprecated display:flex statements

**Comment by JDorpinghaus** [comment]
Added deprecated flex-direction:column statements

**Comment by JDorpinghaus** [comment]
Added deprecated -ms-flex statement, questions now display properly. Show Comments does not function.

**Comment by JDorpinghaus** [comment]
Everything is functional in Internet Explorer 11, however due to a known bug questions are top-aligned and not centered. This is a minor annoyance and doesn't affect the usability of the site.

See http://stackoverflow.com/questions/19371626/flexbox-not-centering-vertically-in-ie for more information.

**Comment by JDorpinghaus** [comment]
https://connect.microsoft.com/IE/feedback/details/802625/min-height-and-flexbox-flex-direction-column-dont-work-together-in-ie-10-11-preview

**Comment by CalebAlbers** [comment]
Hey Jacob,

I might be able to help get around the IE quirks, if you want. I've done my
fair share of cross-browser compatible CSS. I know it can be a pain, but
graceful degradation for incompatible or buggy browsers is super helpful
from a UI/UX perspective.

**Comment by JDorpinghaus** [comment]
That would be great Caleb, I'm sure you have a lot more experience with creating quality CSS than I do. I think I was able to work out most of the kinks, the main issue that remains is vertically centering the question title within the question container div, as you can see in the screenshot below (IE on the left, Chrome on the right).
![capture](https://cloud.githubusercontent.com/assets/9485088/8458021/4de99a2a-1fda-11e5-944a-1b9dc1641e8e.PNG)
