### ISSUE TITLE
Creating a new question refreshes the page; should be AJAX

### ISSUE THREAD

**Issue by JDorpinghaus** [KeystoneIT/Ama#38]

**Comment by jsiems** [comment]
Right now many things refresh the page:
Adding a comment, Posting a question and marking a question as answered.

All of these need to be fixed eventually.

**Comment by jsiems** [comment]
All features now do not refresh the page. See commit 
14046958fcffea853e20f64d1bbae64cfb081e19 for marking answer fix
9706a3e314b21710d2fc6cf256199c832f1fa562 for submitting question fix
4dd2a8855f6878df46b4523d68f989e6d77ad056 for submitting comment fix
