### ISSUE TITLE
Set session to last forever

### ISSUE THREAD

**Issue by s1037989** [KeystoneIT/Ama#39]
Session currently expires after one hour.  Once your session expires you'll never be able to "admin" your questions such as edit and delete.  This is by design.  And part of that design is that the system should remember you forever.  This means updating the session default expiration to forever instead of using default one hour.

**Comment by s1037989** [comment]
Doesn't seem to have resolved the issue.

The issue is that after some time you're able to vote again.

**Comment by jsiems** [comment]
Now stores a username using cookies. I believe they last as long as possible, and that they fix this issue.
