### ISSUE TITLE
Selective linkifying

### ISSUE THREAD

**Issue by JDorpinghaus** [KeystoneIT/Ama#51]
Currently, only URLs in comments that aren't owned by the current user are replaced with anchor tags. This is to prevent interference with clicking to edit comments that are owned by the current user. There is probably a better way to do this, maybe add a dedicated 'edit question' button (next to the flag/delete buttons)?

Titles are currently not linkified at all for the same reason.

**Comment by s1037989** [comment]
I think I know what you mean...  I think both the div (question) and the anchor (link) can have a link.  In other words, clicking on the actual link supersedes clicking on the div and you don't edit the question, but clicking on the div has no link and therefore edits the questions.

Does that make sense?  What do you think?

**Comment by JDorpinghaus** [comment]
Yep, that worked and has been implemented for question titles.

**Comment by s1037989** [comment]
Great!  Remember to push your commits.  Also, a good convention would be make your commit title "blah blah blah, closes #51", or conversely, come back here and comment "Closes abcdef" (where abcdef is the commit SHA) and close.

**Comment by JDorpinghaus** [comment]
Got it, and now that I'm pretty familiar with GitHub I completely understand why. It's so convenient to click on those little commit/issue hyperlinks vs. manually navigating there!

**Comment by JDorpinghaus** [comment]
Fixed in 4c25703 and 511abc8

**Comment by s1037989** [comment]
Awesome, Jacob!  You're killing it!!
