### ISSUE TITLE
Odd question width - might be due to tables fix?

### ISSUE THREAD

**Issue by JDorpinghaus** [KeystoneIT/Ama#52]
![](http://i.imgur.com/OwyI6gT.png)

**Comment by s1037989** [comment]
Are you referring to my commit: 031b6a1?  I'd _totally_ believe it.  My "fix" was awful, just didn't know how to do it appropriately with divs and css.

Any ideas what you could do to fix the formatting and not have text flow outside it's borders?

**Comment by s1037989** [comment]
Updated production Ama from your latest commits!

Uh-oh!  Now all the answered questions are centered!

**Comment by jsiems** [comment]
fixed #61 
layout refactoring has fixed this issue
