### ISSUE TITLE
Line break line breaks

### ISSUE THREAD

**Issue by s1037989** [KeystoneIT/Ama#53]
People press enter (\n) when they enter questions and comments.  Let's convert those to HTML <br> tags so that someone's line break is actually acknowledged.

**Comment by mowgli29** [comment]
I'm not understanding fully. What would this do for us?

**Comment by JDorpinghaus** [comment]
For example, if I create a new question or comment with this text:

```
Line break test

Lower line
```

It will appear as:
`Line break test Lower line`

We should parse the input string and convert any newline characters into HTML <br> tags to preserve the user's line spacing.

**Comment by jsiems** [comment]
fixed #61 
it reads the question or comment before, everywhere a new line is found, it inserts <br/>
