### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by s1037989** [KeystoneIT/Ama#54]
Let's start versioning Ama and even display the Ama version on the website somewhere...

**Comment by JDorpinghaus** [comment]
I added a version variable to the .conf file that now displays in the top right corner for now, I'm sure there's a better way to do this though.

**Comment by CalebAlbers** [comment]
Perhaps look at Github [Release Tags](https://help.github.com/articles/about-releases/) for versioning? I've used
it for Atom.io packages before and it is pretty slick.

**Comment by jsiems** [comment]
fixed #61 
added to top of page
