### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by s1037989** [KeystoneIT/Ama#56]
Feature: Provide ability to sort questions by create date and date of last comment

Reason: Once a question is answered, it gets lost in the sea of previously answered questions.  If we asked a question and missed the TGIF that it was on, it's difficult to track the question down and figure out what the answer was.

Priority: Low

Reported by: @mayfieldtechnologies

**Comment by jsiems** [comment]
An idea exists:

different tabs

One tab for unanswered questions
One tab for answered questions
One tab for my Questions

Each tab will have its own sorting methods, by date old, by date new, by upvotes, etc...

Also a good idea is to try and implement a searching feature so users can search for a specific date or week and see all questions from that week, or search for keywords andsee all questions with those key words.

Also the idea came up to add tags to question to help with sorting them into categories.

**Comment by jsiems** [comment]
didnt mean to hit close

**Comment by jsiems** [comment]
Closed by commit f86293cbc383e73970f1a755236639a3a03c24eb
and 3eead9c480b72ee63d419ff02d88158d527b8258
and 667bdaefae118f782058652be65948e7b9c4ec95
