### ISSUE TITLE
Comments vulnerable to Cross Site Scripting

### ISSUE THREAD

**Issue by meyerben** [KeystoneIT/Ama#58]
Please don't tell anybody.

**Comment by meyerben** [comment]
After playing around. This reminded me of issue #47.
In its current state, we can add pictures and bold text and other formatting to comments. It doesn't make sense to keep it how it is, but a possible enhancement for the future would be allowing some basic formatting like hyperlinks or text formatting

**Comment by s1037989** [comment]
Great observation!

I'd suggest stripping all HTML from posted content, but supporting [Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet).  What do you think?

**Comment by meyerben** [comment]
This is my first time hearing about markdown, but it looks like it would be perfect.

In the meantime, I've created a partial fix that encodes less than, greater than, and ampersand
