### ISSUE TITLE
Add / Edit / Remove Comments

### ISSUE THREAD

**Issue by s1037989** [KeystoneIT/Ama#6]
Just like questions.

**Comment by JDorpinghaus** [comment]
Added reply, mark as answer, edit, and delete buttons to comments

**Comment by JDorpinghaus** [comment]
The reply button is fully functional

**Comment by JDorpinghaus** [comment]
The edit button opens a page to edit a comment but does not have the comment preloaded and does not properly update the comment

**Comment by JDorpinghaus** [comment]
Comment is now preloaded on edit page

**Comment by JDorpinghaus** [comment]
Clicking on comment now redirects to comment edit page

**Comment by JDorpinghaus** [comment]
Delete comment is fully functional; Ajax instantly removes comment from page

**Comment by JDorpinghaus** [comment]
Adding, editing, and removing comments are all fully functional features.
