### ISSUE TITLE
Automatic Votes Error

### ISSUE THREAD

**Issue by jsiems** [KeystoneIT/Ama#66]
When a vote is cast on mobile, it does not automatically upvote it. Instead, it automatically upvotes it for the desktop version on the site at the same time.

**Comment by s1037989** [comment]
Can you explain the process by which this is possible? And what must be
done differently to resolve it?

**Comment by jsiems** [comment]
I don't know for sure what is causing this bug. It looks like it can happen either way, sometimes when you make a question on one device it automatically upvotes it for another and not the one you made the question on, and sometimes you make it on the other device and vice versa, and sometimes it works totally fine. 

And whats even weirder is that even though it doesn't upvote it automatically for you, it still knows that you are the owner of the question.

My best guess is that when two people are on the page at the same time, the server confuses the two usernames somewhere in the creating a question and voting process, and assigns the question creator to the one that actually created it and votes up for the other username currently on the server

How to fix it? I have no idea.
