### ISSUE TITLE
Make Code More Readable

### ISSUE THREAD

**Issue by jsiems** [KeystoneIT/Ama#71]
I was thinking about splitting the massive 750 line scripts.js file into multiple files with appropriate names to make our code more readable. For example, we could move all of the code relating to the Question object and Comment object into their own js file, to show that they can be used independent of all the other code as their own object types.

I don't know if this is a good idea, or if it will make our code harder to read and/or make it harder to find things.

I will wait to change anything until I get some feedback on this idea.

**Comment by jsiems** [comment]
I did some research on the internet, and most sources claim that it is better to have one big js file with all required js to minimize loading times. I will leave all code in the same js file for now.

**Comment by s1037989** [comment]
Checkout [AssetPack](https://github.com/jhthorsen/mojolicious-plugin-assetpack).
