### ISSUE TITLE
Flag questions and comments

### ISSUE THREAD

**Issue by s1037989** [KeystoneIT/Ama#8]
API is similar to voting.  This allows simply flagging a question or comment as inappropriate.  When flagged, let's have the font color and background be black, as you would redact a document.  So if a question or comment is flagged, it's redacted.  You can unflag to unredact.

Eventually, we'll implement users and admin and only admins will be able to unflag.

**Comment by JDorpinghaus** [comment]
Flagging/unflagging questions is now supported and updates instantly when clicked.

**Comment by JDorpinghaus** [comment]
Flagging/unflagging comments is now supported and updates instantly when clicked.
