### ISSUE TITLE
Song can not be played

### ISSUE THREAD

**Issue by georgepollastri** [KeystoneIT/Ama#80]
was unable to play because the decoder (MPEG-4 AAC decoder) can not be found - This is the error I get when I try to play some songs, but the songs play fine in my other players. 

Please send me an E mail when problem is resolved.  Thank You .

**Comment by jsiems** [comment]
who are you

**Comment by jsiems** [comment]
You are in the wrong repository. This repository is for a web application for anonymous question asking.
