### ISSUE TITLE
Votes are incorrect on initial load

### ISSUE THREAD

**Issue by s1037989** [KeystoneIT/Ama#9]
The SQL for Model/Questions/all is wrong.  It's summing votes for all rows, including each row for each comment.

The solution is to multi-step the Perl code with multiple queries or use stored procedures.  The latter would allow for select \* from questions and for each question it finds it can call a stored procedure that gets the answer for this question and also gets the votes for this question.

**Comment by JDorpinghaus** [comment]
Fixed using a stored procedure in the PSQL database to return votes.
